
working_directory: "./repos"

repositories:
    example:
        enabled: false
        from: "https://github.com/sea-kg/pipeline-editor-s5"
        to: "http://root:some@another.server.com/sea5kg/pipeline-editor-s5"
